name: 'dbt Simple Action'
description: 'An action that allows for multiple DBT actions using NixOS and Flakes'
author: 'CedricLeong'
inputs:
  dbt-snowflake:
    description: Installs only the snowflake adapter.
  dbt-postgres:
    description: Installs only the postgreSQL adapter.
  dbt-bigquery:
    description: Installs only the bigquery adapter.
  dbt-redshift:
    description: Installs only the redshift adapter.
branding:
  icon: 'truck'
  color: 'blue'
outputs:
  output:
    description: "Success or failure of the action"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v28
    - id: install-dbt
      if: ${{ !inputs.dbt-snowflake && !inputs.dbt-postgres && !inputs.dbt-bigquery && !inputs.dbt-redshift }}
      shell: bash
      run: nix profile install github:CedricLeong/dbt-action-nix
    - id: install-snowflake
      if: ${{ inputs.dbt-snowflake }}
      shell: bash
      run: nix profile install github:CedricLeong/dbt-action-nix/dbt-snowflake
    - id: install-postgres
      if: ${{ inputs.dbt-postgres }}
      shell: bash
      run: nix profile install github:CedricLeong/dbt-action-nix/dbt-postgres
    - id: install-bigquery
      if: ${{ inputs.dbt-bigquery }}
      shell: bash
      run: nix profile install github:CedricLeong/dbt-action-nix/dbt-bigquery
    - id: install-redshift
      if: ${{ inputs.dbt-redshift }}
      shell: bash
      run: nix profile install github:CedricLeong/dbt-aciton-nix/dbt-redshift
